server:
  port: ${PORT:8080}

spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      use_sql_comments: true