# ===============================
# MAIN
# ===============================
server:
  port: ${PORT:8080}
  tomcat:
    max-swallow-size: -1

spring:
  config:
    import: optional:file:.env[.properties]
  mvc:
    hidden-method:
      filter:
        enabled: true

  # ==================================
  #   Redis
  # ==================================
  session:
    redis:
      namespace: weather-app
  data:
    redis:
      port: ${REDIS_SERVICE_PORT}
      host: ${REDIS_SERVICE_HOST}
      password: ${SPRING_REDIS_PASSWORD}

  # ===============================
  # DATABASE
  # ===============================
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect

  # ==================================
  #   Thymeleaf
  # ==================================
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  # ==================================
  #   Multipart data
  # ==================================
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

# ==================================
#   MinIO
# ==================================
minio:
  client:
    endpoint: ${MINIO_CLIENT_ENDPOINT}
    user: ${MINIO_CLIENT_USER}
    password: ${MINIO_CLIENT_PASSWORD}
    bucket-name: root

# ==================================
#   Actuator HEALTH CHECK
# ==================================
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 1000

logging:
  level:
    org.springframework.boot.actuate: DEBUG